# Generated by Django 3.2.9 on 2021-11-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Схему',
                'verbose_name_plural': 'Схемы',
            },
        ),
        migrations.CreateModel(
            name='GeofenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя группы, геозоны которой будут обрабатываться', max_length=50, verbose_name='Название группы')),
                ('active', models.BooleanField(default=True, help_text='Показывается ли группа геозон на карте', verbose_name='Включено')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_groups', to='autograph.schema', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Группу геозон',
                'verbose_name_plural': 'Группы геозон',
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя группы, машины которой будут обрабатываться', max_length=50, verbose_name='Название группы')),
                ('active', models.BooleanField(default=True, help_text='Показывается ли группа машин на карте', verbose_name='Включено')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='autograph.schema', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Группу машин',
                'verbose_name_plural': 'Группы машин',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Показывается ли машина на карте', verbose_name='Включено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='autograph.devicegroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Машину',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
