# Generated by Django 3.2.9 on 2021-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
