# Generated by Django 3.2.9 on 2021-11-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autograph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('geofence_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Показывается ли геозона на карте', verbose_name='Включено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='autograph.geofencegroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Геозону',
                'verbose_name_plural': 'Геозоны',
            },
        ),
    ]
