# Generated by Django 3.2.9 on 2021-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograph', '0002_alter_schema_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schema',
            options={'verbose_name': 'схему', 'verbose_name_plural': 'схемы'},
        ),
        migrations.AlterField(
            model_name='schema',
            name='schema_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
    ]
