# Generated by Django 3.2.9 on 2021-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograph', '0003_auto_20211125_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя группы, которая будет обрабатываться', max_length=50, verbose_name='Имя группы')),
            ],
        ),
    ]
