# Generated by Django 3.2.9 on 2021-11-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograph', '0005_auto_20211125_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Машину', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=True, help_text='Показывается ли машина на карте', verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='active',
            field=models.BooleanField(default=True, help_text='Показывается ли группа машин на карте', verbose_name='Включено'),
        ),
    ]
