# Generated by Django 3.2.9 on 2021-11-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograph', '0006_auto_20211125_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
    ]
