# Generated by Django 3.2.9 on 2021-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograph', '0008_alter_device_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя группы, геозоны которой будут обрабатываться', max_length=50, verbose_name='Название группы')),
                ('active', models.BooleanField(default=True, help_text='Показывается ли группа геозоны на карте', verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Группу геозон',
                'verbose_name_plural': 'Группы геозон',
            },
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'verbose_name': 'Схему', 'verbose_name_plural': 'Схемы'},
        ),
    ]
