# Generated by Django 3.2.9 on 2021-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograph', '0009_auto_20211125_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofencegroup',
            name='active',
            field=models.BooleanField(default=True, help_text='Показывается ли группа геозон на карте', verbose_name='Включено'),
        ),
    ]
